export { suggestCanonical } from './core/rules.js'
export { analyzeFile } from './core/analyzer.js'
export { fixFile } from './core/fixer.js'
export { scanFiles } from './core/scanner.js'
export type { Config, Suggestion } from './core/rules.js'
export type { Finding } from './core/analyzer.js'
